#!/usr/bin/python3

import requests
import os

API_KEY = os.environ.get("WEATHER_API_KEY")
CITY = os.environ.get("WEATHER_CITY_CODE", 6324729)  # Defaults to Halifax


BANNER = """/---------------------/
/ (: 8<D 8<D 8<D :)   /
/ Welcome to WEATHER /
/___________________/"""


def to_c(temp):
    return round(
        temp - 273.15,
        1
    )


def get_data():
    url = "http://api.openweathermap.org/data/2.5/forecast?id={}&appid={}".format(CITY, API_KEY)
    response = requests.get(url)
    if response.status_code != 200:
        return
    return response.json()


def main():
    print(BANNER)

    if not API_KEY:
        print("We couldn't get your Key")
        return

    data = get_data()

    if not data:
        print("Something went wrong.")
        return

    for thing in data['list']:
        temp = thing['main']['temp']
        temp_in_c = to_c(temp)
        print(thing['dt_txt'], temp_in_c, "C")


if __name__ == "__main__":
    main()
